/**:
    ros__parameters:
        image_transport: raw    # image format
        family: 16h5           # tag family name
        size: 0.080            # tag edge size in meter
        max_hamming: 2         # maximum allowed hamming distance (corrected bits)
        min_decision_margin: 25.0  # minimum decision margin (confidence threshold)

        # see "apriltag.h" 'struct apriltag_detector' for more documentation on these optional parameters
        detector:
            threads: 1          # number of threads
            decimate: 1.5       # decimate resolution for quad detection (higher = more stable)
            blur: 0.5           # sigma of Gaussian blur for quad detection (slightly blur to reduce noise)
            refine: True        # snap to strong gradients
            sharpening: 0.0     # reduce sharpening to minimize noise
            debug: False        # write additional debugging images to current working directory

        pose_estimation_method: "pnp"   # method for estimating the tag pose

        # optional list of tags
        tag:
            ids: [0,1,2]            # tag ID
            frames: [tag_0, tag_1, tag_2]  # optional frame name
            sizes: [0.0771, 0.080, 0.080]   # optional tag-specific edge size 